#https://github.com/marketplace/actions/hub-mirror-action
name: syncToGitee
on:
  schedule:
    - cron: '0 17 * * *' # 01:00 Asia/Shanghai (UTC+8)
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master

        with:
          src: github/tauskills
          dst: gitee/tauskills
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          account_type: org
          
